<a href="https://colab.research.google.com/github/Aatka-Saleem/ML-Core-Implementations/blob/main/01-Data-Foundations/Data_Preprocessing_and_Feature_Engineering_Feature_Scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## FEATURE SCALING EXERCISE

### Imports

In [ ]:
import pandas as pd
import numpy as np

### Problem: The Boston House Pricing

**Dataset Description**

Boston House pricing dataset is provided with this notebook as 'Dataset_Boston.csv' file.

The details of this dataset are as follows:

Number of Instances: 506
Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

Attribute Information (in order):
- CRIM     per capita crime rate by town
- ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
- INDUS    proportion of non-retail business acres per town
- CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
- NOX      nitric oxides concentration (parts per 10 million)
- RM       average number of rooms per dwelling
- AGE      proportion of owner-occupied units built prior to 1940
- DIS      weighted distances to five Boston employment centres
- RAD      index of accessibility to radial highways
- TAX      full-value property-tax rate per \$10,000
- PTRATIO  pupil-teacher ratio by town
- B        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
- LSTAT    percentage of lower status of the population
- MEDV     Median value of owner-occupied homes in $1000's

Missing Attribute Values: None

Creator: Harrison, D. and Rubinfeld, D.L.

This Boston House Pricing data has been taken from a reaserch paper, which can be found at
[Source: Original research paper](https://deepblue.lib.umich.edu/bitstream/handle/2027.42/22636/0000186.pdf?sequence=1&isAllowed=y)

**Loading Data**

In [ ]:
#Reading the file into a dataframe
data=pd.read_csv('Dataset_Boston.csv')
#Displaying the read contents
data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

**Exploring Data**

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    int64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  PRICE    506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB

In [ ]:
data.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [ ]:
data.shape

(506, 14)

### Scaling Data - Normalization

In [ ]:
#Let us normalize the PTRATIO column using the normalization formula \discussed in class.
data['PTRATIO']=(data['PTRATIO']-data['PTRATIO'].min())/(data['PTRATIO'].max()-data['PTRATIO'].min())
#Let us check the dataset
data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,0.287234,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,0.553191,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,0.553191,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,0.648936,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,0.648936,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,0.893617,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,0.893617,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,0.893617,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,0.893617,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,0.893617,396.90,7.88,11.9

In [ ]:
#Let us check the min and max value of this normalized column now.
print('Minimum value is',data['PTRATIO'].min())
print('Maximum value is',data['PTRATIO'].max())

Minimum value is 0.0
Maximum value is 1.0

In [ ]:
#An alternate way is to use methods from sklearn package.
#Let us use this alternate method now to normalize LSTAT column.

#It is a 2-step process. We define an object of MinMaxScaler type first,
#and then call the method fit_transform on this object to perform normalization.
#The fit_transform method takes and ndarray of shape (n_samples, n_features).

#Defining min-max scaler object
from sklearn.preprocessing import MinMaxScaler
minmax_scaler = MinMaxScaler()

#Normailize data
data['LSTAT']=pd.DataFrame(minmax_scaler.fit_transform(data[['LSTAT']]))
#Note that fit_transform method returns a ndarray, so we need to typecast it back to dataframe before placong it back into out dataset.

#this method can be run on whole dataset at once to normalize the all the columns in one go.
#Try it out if you want using the following command.
#column_headers=['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT','PRICE']
#data=pd.DataFrame(minmax_scaler.fit_transform(data),columns=column_headers)
data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,0.287234,396.90,0.089680,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,0.553191,396.90,0.204470,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,0.553191,392.83,0.063466,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,0.648936,394.63,0.033389,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,0.648936,396.90,0.099338,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,0.893617,391.99,0.219095,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,0.893617,396.90,0.202815,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,0.893617,396.90,0.107892,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,0.893617,393.45,0.131071,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,0.893617,396.90,0.169702,11.9

In [ ]:
#Let us check the min and max value of this normalized column now.
print('Minimum value is',data['LSTAT'].min())
print('Maximum value is',data['LSTAT'].max())

Minimum value is 0.0
Maximum value is 0.9999999999999998

### Scaling Data - Standardization

In [ ]:
#Let us run describe method again and observe standard deviation and mean of various features.
data.describe()
# see row 2 and row 3 for mean and standard deviation respectively.

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,0.622929,356.674032,0.301409,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,0.230313,91.294864,0.197049,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,0.000000,0.320000,0.000000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,0.510638,375.377500,0.144040,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,0.686170,391.440000,0.265728,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,0.808511,396.225000,0.420116,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,1.000000,396.900000,1.000000,50.000000

In [ ]:
#Let us standardize the ZN column.
#std and mean are the methods that can be used to find mean and standard deviation of a feature or all features.
data['ZN']=(data['ZN']-data['ZN'].mean())/data['ZN'].std()
#Let us check the dataset description now.
data.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
count,506.000000,5.060000e+02,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,6.319056e-17,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,0.622929,356.674032,0.301409,22.532806
std,8.601545,1.000000e+00,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,0.230313,91.294864,0.197049,9.197104
min,0.006320,-4.872402e-01,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,0.000000,0.320000,0.000000,5.000000
25%,0.082045,-4.872402e-01,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,0.510638,375.377500,0.144040,17.025000
50%,0.256510,-4.872402e-01,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,0.686170,391.440000,0.265728,21.200000
75%,3.677083,4.872402e-02,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,0.808511,396.225000,0.420116,25.000000
max,88.976200,3.800473e+00,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,1.000000,396.900000,1.000000,50.000000

In [ ]:
#Let us view the dataset too.
data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
0,0.00632,0.284548,2.31,0,0.538,6.575,65.2,4.0900,1,296,0.287234,396.90,0.089680,24.0
1,0.02731,-0.487240,7.07,0,0.469,6.421,78.9,4.9671,2,242,0.553191,396.90,0.204470,21.6
2,0.02729,-0.487240,7.07,0,0.469,7.185,61.1,4.9671,2,242,0.553191,392.83,0.063466,34.7
3,0.03237,-0.487240,2.18,0,0.458,6.998,45.8,6.0622,3,222,0.648936,394.63,0.033389,33.4
4,0.06905,-0.487240,2.18,0,0.458,7.147,54.2,6.0622,3,222,0.648936,396.90,0.099338,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,-0.487240,11.93,0,0.573,6.593,69.1,2.4786,1,273,0.893617,391.99,0.219095,22.4
502,0.04527,-0.487240,11.93,0,0.573,6.120,76.7,2.2875,1,273,0.893617,396.90,0.202815,20.6
503,0.06076,-0.487240,11.93,0,0.573,6.976,91.0,2.1675,1,273,0.893617,396.90,0.107892,23.9
504,0.10959,-0.487240,11.93,0,0.573,6.794,89.3,2.3889,1,273,0.893617,393.45,0.131071,22.0
505,0.04741,-0.487240,11.93,0,0.573,6.030,80.8,2.5050,1,273,0.893617,396.90,0.169702,11.9

In [ ]:
#Let us check the min and max value of this normalized column now.
print('Minimum value is',data['ZN'].min())
print('Maximum value is',data['ZN'].max())

Minimum value is -0.4872401872268264
Maximum value is 3.800473460369246

In [ ]:
#An alternate way is to use methods from skleyarn package.
#Let us use this alternate method now to normalize INDUS column.

#It is a 2-step process. We define an object of StandardScaler type first,
#and then call the method fit_transform on this object to perform standardization.
#The fit_transform method takes and ndarray of shape (n_samples, n_features).

#Defining standard scaler object
from sklearn.preprocessing import StandardScaler
stan_scaler = StandardScaler()

#Normailize data
data['INDUS']=pd.DataFrame(stan_scaler.fit_transform(data[['INDUS']]))
#Note that fit_transform method returns a ndarray, so we need to typecast it back to dataframe before placong it back into out dataset.

#this method can be run on whole dataset at once to normalize the all the columns in one go.
#Try it out if you want using the following command.
#data=pd.DataFrame(stan_scaler.fit_transform(data))

In [ ]:
#Let us check the dataset description now.
data.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
count,506.000000,5.060000e+02,5.060000e+02,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,6.319056e-17,2.106352e-16,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,0.622929,356.674032,0.301409,22.532806
std,8.601545,1.000000e+00,1.000990e+00,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,0.230313,91.294864,0.197049,9.197104
min,0.006320,-4.872402e-01,-1.557842e+00,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,0.000000,0.320000,0.000000,5.000000
25%,0.082045,-4.872402e-01,-8.676906e-01,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,0.510638,375.377500,0.144040,17.025000
50%,0.256510,-4.872402e-01,-2.110985e-01,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,0.686170,391.440000,0.265728,21.200000
75%,3.677083,4.872402e-02,1.015999e+00,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,0.808511,396.225000,0.420116,25.000000
max,88.976200,3.800473e+00,2.422565e+00,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,1.000000,396.900000,1.000000,50.000000

In [ ]:
#Let us check the min and max value of this normalized column now.
print('Minimum value is',data['INDUS'].min())
print('Maximum value is',data['INDUS'].max())
#observe the range is pretty much similar to that of ZN that we standardized earlier.

Minimum value is -1.5578417886292542
Maximum value is 2.422565163932244

### Task for you

Try scaling other columns of the dataset.